### ISSUE TITLE
Syntax error while compiling example program

### ISSUE THREAD

**Issue by mrhmouse** [kfl/mosml#35]
While compiling one of the example programs, I get a syntax error:
```sh-session
    $ mosmlc ./examples/modules/array.sml
    File "./examples/modules/array.sml", line 7, characters 0-9:
    ! signature  Array  =
    ! ^^^^^^^^^
    ! Syntax error.
```
This also happens with this simple program:
```sml
    structure MyList =
      struct
        fun each _ [] = ()
          | each f (x :: xs) = (f x; each f xs)
      end;
    
    val _ = MyList.each print ["Hello, world!\n"];
```
```sh-session
    $ ./bin/mosmlc example.sml
    File "example.sml", line 7, characters 0-3:
    ! val _ = MyList.each print ["Hello, world!\n"];
    ! ^^^
    ! Syntax error.
```

Both files run properly with the interpreter, `mosml`. This is running at tag `ver-2.10.1` on Linux 4.1.4, armv6l.

**Comment by crusso** [comment]
Hi Jordon,

It’s been while since I’ve used mosml  but if I recall correctly it looks to me that these files are not valid  “structure-mode” compilation units. To compile them you have to use mosmlc option  -toplevel. See sections 5 and 6 of the manual.

http://mosml.org/manual.pdf

Hope that works,
Claudio

**Comment by mrhmouse** [comment]
Thanks, @crusso! That seems to have been the problem :sweat_smile:
